### ISSUE TITLE
slack issue

### ISSUE THREAD

**Issue by matthijs-neijenhuijs** [tylercd100/lern#34]
In slack on a mobile phone, the message are with a red background. Hard to read with black text.

**Comment by tylercd100** [comment]
Hey @isomis this is because LERN logs the exception on the **critical** level then sends that over to Monolog which generates the red looking slack message. I could make this work by simply adding another config value to change the log level to something else other than critical. Let me know if that would work for you?

**Comment by matthijs-neijenhuijs** [comment]
Yes, that would work!! Nice packages by the way!

**Comment by tylercd100** [comment]
@isomis Please give version 3.6.0 a try.

Please notice the `log_level` key in the [config/lern.php](https://github.com/tylercd100/lern/blob/master/config/lern.php) file. Try setting it to `debug` or `info`.

#35 

Please reopen this issue if it doesn't work :)

**Comment by matthijs-neijenhuijs** [comment]
Yes thnx!
